# Generated by Django 4.1.7 on 2023-03-01 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Day Trek', 'Day Trek'), ('Trekking & Camping', 'Trekking & Camping'), ('Night Trek & Camping', 'Night Trek & Camping'), ('Tours', 'Tours')], default='Day Trek', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_name', models.CharField(max_length=100)),
                ('op_phone', models.CharField(max_length=13, unique=True)),
                ('op_email', models.EmailField(max_length=254)),
                ('op_rating', models.CharField(max_length=5)),
                ('trip_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('avg_rating', models.CharField(max_length=5)),
                ('count', models.IntegerField()),
                ('price', models.CharField(max_length=8)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Easy to Moderate', 'Easy to Moderate'), ('Moderate to Hard', 'Moderate'), ('Moderate to Hard', 'Moderate to Hard'), ('Hard', 'Hard')], default='Easy to Moderate', max_length=100)),
                ('category', models.ForeignKey(default='Day Trek', on_delete=django.db.models.deletion.PROTECT, to='trip_operator.category')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_operator', to='trip_operator.operator')),
            ],
        ),
    ]
