# Generated by Django 4.1.7 on 2023-03-01 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_operator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-avg_rating',)},
        ),
        migrations.AlterField(
            model_name='trip',
            name='avg_rating',
            field=models.CharField(default='5', max_length=5),
        ),
        migrations.CreateModel(
            name='TripInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('startpoint', models.CharField(max_length=200)),
                ('pickup_locations', models.TextField(null=True)),
                ('altitude', models.CharField(max_length=10, null=True)),
                ('distance', models.CharField(max_length=10, null=True)),
                ('itinerary', models.TextField(null=True)),
                ('additional_info', models.TextField(null=True)),
                ('rating', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('for_trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip_operator.trip')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
    ]
