# Generated by Django 4.1.7 on 2023-03-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_operator', '0002_alter_trip_options_alter_trip_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_rating',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
