# Generated by Django 4.1.7 on 2023-03-05 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip_operator', '0003_trip_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinstance',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
