# Generated by Django 4.1.7 on 2023-03-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_operator', '0005_alter_operator_trip_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='op_pass',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
