# Generated by Django 4.1.7 on 2023-03-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_operator', '0006_operator_op_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_pass', models.CharField(max_length=254)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=13)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip_operator.operator')),
            ],
        ),
        migrations.AddField(
            model_name='tripinstance',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='trip_operator.operatoruser'),
        ),
    ]
