# Generated by Django 3.2.12 on 2023-03-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_operator', '0007_operatoruser_tripinstance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='op_logo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
