# Generated by Django 3.2.12 on 2023-03-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_operator', '0009_alter_operator_op_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='op_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
