# Generated by Django 3.2.12 on 2023-03-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_operator', '0010_alter_operator_op_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='op_logo',
        ),
    ]
