# Generated by Django 3.2.12 on 2023-03-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_operator', '0012_operator_op_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='op_logo',
            field=models.ImageField(default=None, upload_to='logos/'),
        ),
    ]
