# Generated by Django 3.2.12 on 2023-03-11 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip_operator', '0012_operator_op_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomad_name', models.CharField(max_length=254)),
                ('nomad_email', models.EmailField(max_length=254)),
                ('nomad_phone', models.CharField(max_length=13)),
                ('nomad_pass', models.CharField(max_length=100)),
            ],
            managers=[
                ('nomad_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('cancelled', models.BooleanField(default=False)),
                ('booking_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('participant_count', models.IntegerField(default=1)),
                ('participants', models.TextField(null=True)),
                ('trek_rating', models.FloatField()),
                ('organizer_rating', models.FloatField()),
                ('for_trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip_operator.tripinstance')),
                ('nomad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.nomad')),
            ],
            options={
                'ordering': ('-booking_date',),
            },
            managers=[
                ('bookingobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
