# Generated by Django 3.2.12 on 2023-03-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomad',
            name='nomad_dp',
            field=models.ImageField(default=None, upload_to='nomad-dps/'),
        ),
    ]
